# Generated by Django 5.2.8 on 2025-12-14 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('backdrop', models.ImageField(upload_to='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_language', models.CharField(max_length=50, null=True)),
                ('content_rating', models.CharField(max_length=10, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
